In [2]:
import torch
from torch import autograd

In [3]:
def sample_model(x):
    w = torch.tensor([[1., 3.], [0., -1.]])
    b = torch.tensor([[0.], [2.]])
    return w.mm(x) + b

In [4]:
sample_model(torch.tensor([[1.], [1.]]))

tensor([[4.],
        [1.]])

In [5]:
def compute_jacobian(outputs: torch.Tensor, inputs: torch.Tensor):
    k, _ = outputs.size()
    n, _ = inputs.size()
    
    res = torch.zeros(k, n)

    for i in range(0, n):
        grad_outputs = torch.zeros(n,1)
        grad_outputs[i] = 1.
        grad = autograd.grad(outputs, inputs, grad_outputs=grad_outputs, retain_graph=True)[0]
        res[:,i:i+1] = grad

    return res.t() # transpose because autograd.grad calculates J.t() * v

In [6]:
x = torch.tensor([[1.], [1.]], requires_grad=True)
y = sample_model(x)

compute_jacobian(y, x)

tensor([[ 1.,  3.],
        [ 0., -1.]])

In [7]:
def compute_jacobian_row_vector(outputs: torch.Tensor, inputs: torch.Tensor):
    k = outputs.size()[0]
    n = inputs.size()[0]
    
    res = torch.zeros(k, n)

    for i in range(0, n):
        grad_outputs = torch.zeros(n)
        grad_outputs[i] = 1.
        grad = torch.autograd.grad(outputs, inputs, grad_outputs=grad_outputs, retain_graph=True)[0]
        res[:,i:i+1] = grad.reshape(2,1)

    return res.t() # transpose because autograd.grad calculates J.t() * v

In [18]:
x = torch.tensor([1., 1.], requires_grad=True)
y = sample_model(x.reshape(2, 1)).reshape([2])

compute_jacobian_row_vector(y, x)

tensor([[ 1.,  3.],
        [ 0., -1.]])